### ISSUE TITLE
`null` character

### ISSUE THREAD

**Issue by isomorphisms** [s-u/base64enc#1]
Trying to do [this](http://stackoverflow.com/a/11049483/563329) via R rather than perl, R chokes on the `"\000.........\000......."` part. (perl does fine)

**Comment by s-u** [comment]
R doesn't support embedded NULs in strings, so you have to use a raw vector instead, for example

``` r
> base64encode(c(0L, charToRaw("myemail@gmail.com"), 0L, charToRaw("mypassword")))
[1] "AG15ZW1haWxAZ21haWwuY29tAG15cGFzc3dvcmQ="
```
